# tasks file
---
- name: install dependencies
  ansible.builtin.apt:
    name: "{{ swapfile_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - swapfile
    - swapfile-install
    - swapfile-install-dependencies

- name: swap file
  when: not swapfile_size | bool
  tags:
    - configuration
    - swapfile
  block:
    - name: write swap file  # noqa command-instead-of-module
      ansible.builtin.command: >
        fallocate -l {{ swapfile_size }} {{ swapfile_file }}
      args:
        creates: "{{ swapfile_file }}"
      register: _write_swapfile
      tags:
        - swapfile-write-file

    - name: set swap file permissions
      ansible.builtin.file:
        path: "{{ swapfile_file }}"
        owner: root
        group: root
        mode: '0600'
      tags:
        - swapfile-set-file-permissions

    - name: create swap file  # noqa command-instead-of-module
      ansible.builtin.command: >
        mkswap {{ swapfile_file }}
      register: _create_swapfile
      changed_when: true
      when: _write_swapfile is changed
      tags:
        - swapfile-mkswap

    - name: enable swapfile  # noqa command-instead-of-module
      ansible.builtin.command: >
        swapon {{ swapfile_file }}
      changed_when: true
      when: _create_swapfile is changed
      tags:
        - swapfile-enable-swapfile

    - name: add swapfile to /etc/fstab
      ansible.posix.mount:
        name: none
        src: "{{ swapfile_file }}"
        fstype: swap
        opts: sw
        passno: '0'
        dump: '0'
        state: present
      tags:
        - swapfile-fstab

- name: configure vm.swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ swapfile_swappiness | string }}"
    reload: true
    state: present
  when: swapfile_swappiness is defined
  tags:
    - configuration
    - swapfile
    - swapfile-vm-swappiness

- name: configure vm.vfs_cache_pressure
  ansible.posix.sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ swapfile_vfs_cache_pressure | string }}"
    reload: true
    state: present
  when: swapfile_vfs_cache_pressure is defined
  tags:
    - configuration
    - swapfile
    - swapfile-vm-vfs-cache-pressure
